INSERT INTO hotel (name,address,city,state,price) VALUES ('Isaac','P.O. Box 964, 2937 Libero Rd.','Merizo','British Columbia','136');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Elliott','P.O. Box 129, 4099 Nascetur Ave','Buena Park','Nunavut','93');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Rajah','786-3145 Dignissim Av.','Laramie','NC','124');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Prescott','5186 Commodo Rd.','Warwick','MN','73');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Samuel','718-2371 Lacus. Avenue','El Monte','Alberta','84');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Garth','P.O. Box 695, 1756 Donec Ave','Seal Beach','Colorado','70');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Garrett','P.O. Box 925, 4396 Semper Rd.','Ephraim','SK','82');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Buckminster','Ap #231-6219 Risus. Street','Dover','ON','125');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Phillip','409-144 Ut, Rd.','Easthampton','Alberta','54');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Dean','558-2740 Sit St.','Gulfport','Quebec','98');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Akeem','Ap #470-860 Enim. Street','Port St. Lucie','AK','200');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Benedict','124-6400 Enim Road','Pulaski','BC','197');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Chaim','P.O. Box 339, 3623 Non Street','Branson','North Carolina','133');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Cody','P.O. Box 673, 6867 Cum Rd.','Astoria','New York','82');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Neville','P.O. Box 151, 8223 Arcu. Rd.','Bossier City','AB','191');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Lars','P.O. Box 271, 8084 Praesent Rd.','Simi Valley','Minnesota','121');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Keith','252-8271 Nunc, St.','Little Rock','YT','193');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Louis','3786 Diam Ave','Fort Lauderdale','NJ','100');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Fuller','5086 Diam Av.','Everett','TN','82');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Elvis','606 Vestibulum, St.','Elmira','ON','61');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Roth','507-8046 Sed St.','Opelousas','NC','163');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Armand','155 Dignissim. St.','Guayanilla','Northwest Territories','174');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Vaughan','667-6122 Augue Rd.','Fayetteville','Ontario','92');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Phelan','809-5081 Eros. Ave','Laredo','ON','139');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Lance','P.O. Box 443, 6387 Malesuada. Ave','Elko','BC','108');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Callum','Ap #364-996 Arcu Street','Lansing','NV','115');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Chaney','P.O. Box 962, 2236 Lorem, Rd.','Rock Springs','IN','57');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Garth','8639 Tortor Rd.','Rancho Palos Verdes','Manitoba','175');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Brent','Ap #803-5388 Pellentesque, St.','Sunnyvale','BC','175');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Perry','P.O. Box 319, 277 Lacus Avenue','Kalamazoo','NU','51');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Porter','P.O. Box 552, 2300 Quam. St.','Slidell','CT','166');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Demetrius','Ap #709-6371 Senectus Av.','Fort Dodge','ON','90');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Dalton','Ap #413-6247 Rhoncus. Av.','Duquesne','North Carolina','102');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Kasper','914-7661 Integer Rd.','Columbia','Massachusetts','126');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Beck','P.O. Box 567, 4276 Dictum St.','Miami Beach','Yukon','102');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Malik','P.O. Box 408, 5801 Velit St.','Fredericksburg','Saskatchewan','200');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Zane','Ap #528-5098 Proin Road','Webster Groves','PE','176');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Armando','584-4923 Felis. Av.','Fontana','CT','121');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Allistair','P.O. Box 268, 650 Tempor St.','Brockton','CO','85');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Ronan','P.O. Box 104, 3738 Libero Street','Flagstaff','KS','107');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Yardley','966 Pretium Rd.','Mentor','BC','171');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Uriah','P.O. Box 693, 6284 Integer Road','Springdale','YT','88');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Mannix','9451 Ut St.','Lake Charles','Virginia','130');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Aristotle','104-407 Mi Street','Gallup','NT','81');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Herman','342-4292 Vitae, St.','Weirton','Florida','184');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Orson','555-8692 Odio, Av.','Concord','Pennsylvania','74');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Chadwick','P.O. Box 228, 2463 Vulputate, Av.','Cranston','NS','157');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Cyrus','P.O. Box 367, 6470 Justo Avenue','Cruz Bay','AB','117');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Conan','5963 Neque St.','Hopkinsville','VT','176');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Christian','6200 Nec, Street','Apple Valley','Alberta','135');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Levi','454-8390 Facilisis Rd.','San Jose','MI','110');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Charles','P.O. Box 869, 8691 Eu St.','Fond du Lac','Manitoba','113');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Lionel','7050 Diam Av.','LaGrange','NL','141');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Geoffrey','2796 Leo. Rd.','Alexandria','Nova Scotia','187');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Hammett','Ap #978-3058 Aliquet St.','Bethlehem','NT','109');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Vaughan','Ap #629-8147 Bibendum. St.','Boulder City','Northwest Territories','197');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Quinlan','P.O. Box 451, 5388 Ut St.','Loudon','Manitoba','64');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Clarke','637-6021 Nonummy Rd.','San Dimas','New Brunswick','107');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Allistair','383-4419 Rhoncus. Rd.','West Hollywood','Nunavut','174');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Cadman','716-8208 Cursus Rd.','North Chicago','WV','56');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Cyrus','Ap #737-7018 Nascetur Rd.','Wynne','Manitoba','159');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Gareth','370-8352 In Ave','Beaumont','OR','64');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Thaddeus','1962 Ut St.','Fargo','VT','190');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Curran','P.O. Box 864, 9583 Congue Street','Jeannette','Ontario','197');
INSERT INTO hotel (name,address,city,state,price) VALUES ('John','684-8275 Dui. Ave','Charleston','Saskatchewan','75');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Roth','121-3082 Vivamus St.','Bossier City','Georgia','90');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Sebastian','686-4332 Sociis Avenue','Bayamon','GA','126');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Ashton','P.O. Box 104, 3306 In Rd.','Gardner','Louisiana','141');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Nathaniel','110-6750 Ac Av.','Charleston','Yukon','77');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Aidan','2912 Odio. Road','La CaÃ±ada Flintridge','Quebec','52');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Perry','P.O. Box 637, 9702 Integer Road','Sheboygan','Quebec','118');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Dane','Ap #565-4476 Purus. Street','New Brunswick','Quebec','75');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Ferdinand','991-6271 Imperdiet Av.','Eatontown','KS','79');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Boris','Ap #402-8046 Integer Rd.','Artesia','Northwest Territories','177');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Stephen','P.O. Box 683, 7750 Molestie Road','Cambridge','MB','121');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Talon','577-9141 Libero Av.','Glen Cove','Utah','90');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Dean','923-1821 A Street','Rosemead','Newfoundland and Labrador','189');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Emmanuel','603 Elit, St.','Waterloo','OH','160');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Peter','Ap #796-6783 Placerat, Road','Urbana','Yukon','195');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Baxter','P.O. Box 946, 3097 Tellus. Road','Marlborough','Newfoundland and Labrador','126');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Guy','P.O. Box 497, 9591 Orci. St.','Johnstown','Montana','57');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Jameson','Ap #703-9052 Semper Av.','Cedar Rapids','KY','141');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Neville','P.O. Box 549, 5919 Elit. St.','Quincy','Prince Edward Island','52');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Damian','4638 A Rd.','Avalon','New Brunswick','179');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Chandler','Ap #923-5495 Egestas. Avenue','Easton','Prince Edward Island','51');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Benjamin','2799 A St.','Corinth','Ontario','169');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Curran','623-3634 Sollicitudin Rd.','Montgomery','Rhode Island','106');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Melvin','P.O. Box 876, 6643 Id Rd.','Colorado Springs','Quebec','193');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Tarik','P.O. Box 609, 9658 Dictum Ave','Joliet','Massachusetts','181');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Noah','Ap #490-3359 Vitae, Rd.','Calabasas','PA','189');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Kermit','Ap #539-275 Ante, St.','Houston','Alberta','55');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Jin','427-1901 Tempor, Rd.','Macon','KY','56');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Patrick','811-3851 Eros. Av.','Topeka','Alberta','139');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Yoshio','465-3017 Nisi. Ave','Webster Groves','Prince Edward Island','99');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Ralph','Ap #348-4304 Fusce Ave','MayagÃ¼ez','MI','87');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Henry','6616 Et St.','Clairton','NY','137');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Jack','Ap #781-2244 Amet Avenue','Glen Cove','SK','132');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Emmanuel','7726 Donec Av.','Cambridge','QC','124');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Dustin','6411 Sem St.','Pittsburgh','WI','172');
INSERT INTO hotel (name,address,city,state,price) VALUES ('Dustin','218-121 Convallis Ave','Stevens Point','ID','181');

